# Generated by Django 4.2.1 on 2023-08-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentmodel',
            options={'verbose_name_plural': 'Rent Requests'},
        ),
    ]
