# Generated by Django 4.2.1 on 2023-08-08 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_rentmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmodel',
            name='days',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='You need to rent a car for at least 1 days.')]),
        ),
    ]
