# Generated by Django 4.2.1 on 2023-08-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rentmodel_car_rented_rentmodel_rented_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentmodel',
            name='rent_until',
            field=models.DateTimeField(default=None),
        ),
    ]
