# Generated by Django 4.2.1 on 2023-08-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_rentmodel_rent_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmodel',
            name='rent_until',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
