# Generated by Django 4.2.1 on 2023-08-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_app', '0016_alter_carlisting_price'),
        ('rent', '0006_alter_rentmodel_rent_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentmodel',
            name='car_rented',
        ),
        migrations.RemoveField(
            model_name='rentmodel',
            name='rented_from',
        ),
        migrations.AlterField(
            model_name='rentmodel',
            name='rented_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rented_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RentLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(auto_now_add=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Car_Rented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.carlisting')),
                ('rent_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rent_Object_Attached', to='rent.rentmodel')),
                ('rented_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rented_from_User', to=settings.AUTH_USER_MODEL)),
                ('rented_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rented_to_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
