# Generated by Django 4.2.1 on 2023-08-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0016_alter_carlisting_price'),
        ('rent', '0007_remove_rentmodel_car_rented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentmodel',
            name='car_rented',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='car_rented_rent_model', to='car_app.carlisting'),
            preserve_default=False,
        ),
    ]
