# Generated by Django 4.2.1 on 2023-08-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_rentlogs_car_rented'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentlogs',
            options={'verbose_name_plural': 'Rent Logs'},
        ),
    ]
