# Generated by Django 4.2.1 on 2023-06-26 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Make')),
                ('model', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Car Model')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('body_style', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Body Style')),
                ('year', models.CharField(max_length=5, validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Year')),
                ('horse_power', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horse Power')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mileage')),
                ('euro', models.CharField(max_length=10, verbose_name='Euro')),
                ('transmission', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Transmission')),
                ('drive_type', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Drive Type')),
                ('engine_type', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Engine Type')),
                ('color', models.CharField(blank=True, max_length=16, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Color')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
