# Generated by Django 4.2.1 on 2023-07-10 16:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('body_style', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Body Style')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Year')),
                ('horse_power', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horse Power')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mileage')),
                ('euro', models.CharField(max_length=10, verbose_name='Euro')),
                ('transmission', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Transmission')),
                ('drive_type', models.CharField(max_length=8, validators=[django.core.validators.MaxLengthValidator(8)], verbose_name='Drive Type')),
                ('engine_type', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Engine Type')),
                ('color', models.CharField(blank=True, max_length=16, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Color')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attached_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars_attached', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[], max_length=16, verbose_name='Make')),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['make'],
                'unique_together': {('make',)},
            },
        ),
        migrations.CreateModel(
            name='PhotoCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_photos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[], max_length=50, verbose_name='Car Model')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car_app.carmake')),
            ],
            options={
                'verbose_name_plural': 'Models',
                'ordering': ['make', 'model'],
                'unique_together': {('make', 'model')},
            },
        ),
        migrations.AddField(
            model_name='carlisting',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manafacturer', to='car_app.carmake'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_Model', to='car_app.carmodel'),
        ),
    ]
