from django.db import migrations


def populate_car_makes(apps, schema_editor):
    CarMake = apps.get_model('car_app', 'CarMake')
    car_make_names = [
        'Acura',
        'Alfa Romeo',
        'Aston Martin',
        'Audi',
        'BMW',
        'Bentley',
        'Buick',
        'Cadillac',
        'Chevrolet',
        'Chrysler',
        'Daewoo',
        'Dodge',
        'FIAT',
        'Ferrari',
        'Fisker',
        'Ford',
        'Freightliner',
        'GMC',
        'Genesis',
        'HUMMER',
        'Honda',
        'Hyundai',
        'INFINITI',
        'Isuzu',
        'Jaguar',
        'Jeep',
        'Kia',
        'Lamborghini',
        'Land Rover',
        'Lexus',
        'Lincoln',
        'Lotus',
        'Lucid',
        'MAZDA',
        'MINI',
        'Maserati',
        'Maybach',
        'McLaren',
        'Mercedes-Benz',
        'Mercury',
        'Mitsubishi',
        'Nissan',
        'Oldsmobile',
        'Panoz',
        'Plymouth',
        'Polestar',
        'Pontiac',
        'Porsche',
        'Ram',
        'Rivian',
        'Rolls-Royce',
        'SRT',
        'Saab',
        'Saturn',
        'Scion',
        'Subaru',
        'Suzuki',
        'Tesla',
        'Toyota',
        'VinFast',
        'Volkswagen',
        'Volvo',
        'smart',
    ]  # Add all car make names
    for name in car_make_names:
        CarMake.objects.create(make=name)


def populate_car_models(apps, schema_editor):
    CarModel = apps.get_model('car_app', 'CarModel')
    CarMake = apps.get_model('car_app', 'CarMake')
    car_models_data = [
        {'make': 'Acura', 'model': 'CL'},
        {'make': 'Acura', 'model': 'ILX'},
        {'make': 'Acura', 'model': 'Integra'},
        {'make': 'Acura', 'model': 'MDX Sport Hybrid'},
        {'make': 'Acura', 'model': 'MDX'},
        {'make': 'Acura', 'model': 'NSX'},
        {'make': 'Acura', 'model': 'RDX'},
        {'make': 'Acura', 'model': 'RL'},
        {'make': 'Acura', 'model': 'RLX Sport Hybrid'},
        {'make': 'Acura', 'model': 'RLX'},
        {'make': 'Acura', 'model': 'RSX'},
        {'make': 'Acura', 'model': 'TL'},
        {'make': 'Acura', 'model': 'TLX'},
        {'make': 'Acura', 'model': 'TSX'},
        {'make': 'Acura', 'model': 'ZDX'},
        {'make': 'Alfa Romeo', 'model': '4C Spider'},
        {'make': 'Alfa Romeo', 'model': '4C'},
        {'make': 'Alfa Romeo', 'model': 'Giulia'},
        {'make': 'Alfa Romeo', 'model': 'Stelvio'},
        {'make': 'Alfa Romeo', 'model': 'Tonale'},
        {'make': 'Aston Martin', 'model': 'DB11'},
        {'make': 'Aston Martin', 'model': 'DB9 GT'},
        {'make': 'Aston Martin', 'model': 'DB9'},
        {'make': 'Aston Martin', 'model': 'DBS Superleggera'},
        {'make': 'Aston Martin', 'model': 'DBS'},
        {'make': 'Aston Martin', 'model': 'DBX'},
        {'make': 'Aston Martin', 'model': 'Rapide S'},
        {'make': 'Aston Martin', 'model': 'Rapide'},
        {'make': 'Aston Martin', 'model': 'Vanquish S'},
        {'make': 'Aston Martin', 'model': 'Vanquish'},
        {'make': 'Aston Martin', 'model': 'Vantage'},
        {'make': 'Aston Martin', 'model': 'Virage'},
        {'make': 'Audi', 'model': 'A3 Sportback e-tron'},
        {'make': 'Audi', 'model': 'A3'},
        {'make': 'Audi', 'model': 'A4 (2005.5)'},
        {'make': 'Audi', 'model': 'A4 allroad'},
        {'make': 'Audi', 'model': 'A4'},
        {'make': 'Audi', 'model': 'A5 Sport'},
        {'make': 'Audi', 'model': 'A5'},
        {'make': 'Audi', 'model': 'A6 allroad'},
        {'make': 'Audi', 'model': 'A6'},
        {'make': 'Audi', 'model': 'A7'},
        {'make': 'Audi', 'model': 'A8'},
        {'make': 'Audi', 'model': 'Q3'},
        {'make': 'Audi', 'model': 'Q4 Sportback e-tron'},
        {'make': 'Audi', 'model': 'Q4 e-tron'},
        {'make': 'Audi', 'model': 'Q5 Sportback'},
        {'make': 'Audi', 'model': 'Q5'},
        {'make': 'Audi', 'model': 'Q7'},
        {'make': 'Audi', 'model': 'Q8'},
        {'make': 'Audi', 'model': 'R8'},
        {'make': 'Audi', 'model': 'RS 3'},
        {'make': 'Audi', 'model': 'RS 4'},
        {'make': 'Audi', 'model': 'RS 5'},
        {'make': 'Audi', 'model': 'RS 6'},
        {'make': 'Audi', 'model': 'RS 7'},
        {'make': 'Audi', 'model': 'RS Q8'},
        {'make': 'Audi', 'model': 'RS e-tron GT'},
        {'make': 'Audi', 'model': 'S3'},
        {'make': 'Audi', 'model': 'S4 (2005.5)'},
        {'make': 'Audi', 'model': 'S4'},
        {'make': 'Audi', 'model': 'S5'},
        {'make': 'Audi', 'model': 'S6'},
        {'make': 'Audi', 'model': 'S7'},
        {'make': 'Audi', 'model': 'S8'},
        {'make': 'Audi', 'model': 'SQ5 Sportback'},
        {'make': 'Audi', 'model': 'SQ5'},
        {'make': 'Audi', 'model': 'SQ7'},
        {'make': 'Audi', 'model': 'SQ8'},
        {'make': 'Audi', 'model': 'TT'},
        {'make': 'Audi', 'model': 'allroad'},
        {'make': 'Audi', 'model': 'e-tron GT'},
        {'make': 'Audi', 'model': 'e-tron S Sportback'},
        {'make': 'Audi', 'model': 'e-tron S'},
        {'make': 'Audi', 'model': 'e-tron Sportback'},
        {'make': 'Audi', 'model': 'e-tron'},
        {'make': 'BMW', 'model': '1 Series'},
        {'make': 'BMW', 'model': '2 Series'},
        {'make': 'BMW', 'model': '3 Series'},
        {'make': 'BMW', 'model': '4 Series'},
        {'make': 'BMW', 'model': '5 Series'},
        {'make': 'BMW', 'model': '6 Series'},
        {'make': 'BMW', 'model': '7 Series'},
        {'make': 'BMW', 'model': '8 Series'},
        {'make': 'BMW', 'model': 'Alpina B7'},
        {'make': 'BMW', 'model': 'M'},
        {'make': 'BMW', 'model': 'M2'},
        {'make': 'BMW', 'model': 'M3'},
        {'make': 'BMW', 'model': 'M4'},
        {'make': 'BMW', 'model': 'M5'},
        {'make': 'BMW', 'model': 'M6'},
        {'make': 'BMW', 'model': 'M8'},
        {'make': 'BMW', 'model': 'X1'},
        {'make': 'BMW', 'model': 'X2'},
        {'make': 'BMW', 'model': 'X3 M'},
        {'make': 'BMW', 'model': 'X3'},
        {'make': 'BMW', 'model': 'X4 M'},
        {'make': 'BMW', 'model': 'X4'},
        {'make': 'BMW', 'model': 'X5 M'},
        {'make': 'BMW', 'model': 'X5'},
        {'make': 'BMW', 'model': 'X6 M'},
        {'make': 'BMW', 'model': 'X6'},
        {'make': 'BMW', 'model': 'X7'},
        {'make': 'BMW', 'model': 'Z3'},
        {'make': 'BMW', 'model': 'Z4 M'},
        {'make': 'BMW', 'model': 'Z4'},
        {'make': 'BMW', 'model': 'Z8'},
        {'make': 'BMW', 'model': 'i3'},
        {'make': 'BMW', 'model': 'i4'},
        {'make': 'BMW', 'model': 'i7'},
        {'make': 'BMW', 'model': 'i8'},
        {'make': 'BMW', 'model': 'iX'},
        {'make': 'Bentley', 'model': 'Arnage'},
        {'make': 'Bentley', 'model': 'Azure T'},
        {'make': 'Bentley', 'model': 'Azure'},
        {'make': 'Bentley', 'model': 'Bentayga'},
        {'make': 'Bentley', 'model': 'Brooklands'},
        {'make': 'Bentley', 'model': 'Continental GT'},
        {'make': 'Bentley', 'model': 'Continental'},
        {'make': 'Bentley', 'model': 'Flying Spur'},
        {'make': 'Bentley', 'model': 'Mulsanne'},
        {'make': 'Buick', 'model': 'Cascada'},
        {'make': 'Buick', 'model': 'Century'},
        {'make': 'Buick', 'model': 'Enclave'},
        {'make': 'Buick', 'model': 'Encore GX'},
        {'make': 'Buick', 'model': 'Encore'},
        {'make': 'Buick', 'model': 'Envision'},
        {'make': 'Buick', 'model': 'LaCrosse'},
        {'make': 'Buick', 'model': 'LeSabre'},
        {'make': 'Buick', 'model': 'Lucerne'},
        {'make': 'Buick', 'model': 'Park Avenue'},
        {'make': 'Buick', 'model': 'Rainier'},
        {'make': 'Buick', 'model': 'Regal Sportback'},
        {'make': 'Buick', 'model': 'Regal TourX'},
        {'make': 'Buick', 'model': 'Regal'},
        {'make': 'Buick', 'model': 'Rendezvous'},
        {'make': 'Buick', 'model': 'Terraza'},
        {'make': 'Buick', 'model': 'Verano'},
        {'make': 'Cadillac', 'model': 'ATS'},
        {'make': 'Cadillac', 'model': 'ATS-V'},
        {'make': 'Cadillac', 'model': 'CT4'},
        {'make': 'Cadillac', 'model': 'CT5'},
        {'make': 'Cadillac', 'model': 'CT6'},
        {'make': 'Cadillac', 'model': 'CT6-V'},
        {'make': 'Cadillac', 'model': 'CTS'},
        {'make': 'Cadillac', 'model': 'CTS-V'},
        {'make': 'Cadillac', 'model': 'Catera'},
        {'make': 'Cadillac', 'model': 'DTS'},
        {'make': 'Cadillac', 'model': 'DeVille'},
        {'make': 'Cadillac', 'model': 'ELR'},
        {'make': 'Cadillac', 'model': 'Eldorado'},
        {'make': 'Cadillac', 'model': 'Escalade ESV'},
        {'make': 'Cadillac', 'model': 'Escalade EXT'},
        {'make': 'Cadillac', 'model': 'Escalade'},
        {'make': 'Cadillac', 'model': 'LYRIQ'},
        {'make': 'Cadillac', 'model': 'SRX'},
        {'make': 'Cadillac', 'model': 'STS'},
        {'make': 'Cadillac', 'model': 'Seville'},
        {'make': 'Cadillac', 'model': 'XLR'},
        {'make': 'Cadillac', 'model': 'XT4'},
        {'make': 'Cadillac', 'model': 'XT5'},
        {'make': 'Cadillac', 'model': 'XT6'},
        {'make': 'Cadillac', 'model': 'XTS'},
        {'make': 'Chevrolet', 'model': '2500 Crew Cab'},
        {'make': 'Chevrolet', 'model': '2500 HD Extended Cab'},
        {'make': 'Chevrolet', 'model': '2500 HD Regular Cab'},
        {'make': 'Chevrolet', 'model': '3500 Crew Cab'},
        {'make': 'Chevrolet', 'model': '3500 Extended Cab'},
        {'make': 'Chevrolet', 'model': '3500 Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Astro Cargo'},
        {'make': 'Chevrolet', 'model': 'Astro Passenger'},
        {'make': 'Chevrolet', 'model': 'Avalanche 1500'},
        {'make': 'Chevrolet', 'model': 'Avalanche 2500'},
        {'make': 'Chevrolet', 'model': 'Avalanche'},
        {'make': 'Chevrolet', 'model': 'Aveo'},
        {'make': 'Chevrolet', 'model': 'Blazer'},
        {'make': 'Chevrolet', 'model': 'Bolt EUV'},
        {'make': 'Chevrolet', 'model': 'Bolt EV'},
        {'make': 'Chevrolet', 'model': 'Camaro'},
        {'make': 'Chevrolet', 'model': 'Captiva Sport'},
        {'make': 'Chevrolet', 'model': 'Cavalier'},
        {'make': 'Chevrolet', 'model': 'City Express'},
        {'make': 'Chevrolet', 'model': 'Classic'},
        {'make': 'Chevrolet', 'model': 'Cobalt'},
        {'make': 'Chevrolet', 'model': 'Colorado Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Colorado Extended Cab'},
        {'make': 'Chevrolet', 'model': 'Colorado Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Corvette'},
        {'make': 'Chevrolet', 'model': 'Cruze Limited'},
        {'make': 'Chevrolet', 'model': 'Cruze'},
        {'make': 'Chevrolet', 'model': 'Equinox'},
        {'make': 'Chevrolet', 'model': 'Express 1500 Cargo'},
        {'make': 'Chevrolet', 'model': 'Express 1500 Passenger'},
        {'make': 'Chevrolet', 'model': 'Express 2500 Cargo'},
        {'make': 'Chevrolet', 'model': 'Express 2500 Passenger'},
        {'make': 'Chevrolet', 'model': 'Express 3500 Cargo'},
        {'make': 'Chevrolet', 'model': 'Express 3500 Passenger'},
        {'make': 'Chevrolet', 'model': 'HHR'},
        {'make': 'Chevrolet', 'model': 'Impala Limited'},
        {'make': 'Chevrolet', 'model': 'Impala'},
        {'make': 'Chevrolet', 'model': 'Lumina'},
        {'make': 'Chevrolet', 'model': 'Malibu (Classic)'},
        {'make': 'Chevrolet', 'model': 'Malibu Limited'},
        {'make': 'Chevrolet', 'model': 'Malibu'},
        {'make': 'Chevrolet', 'model': 'Metro'},
        {'make': 'Chevrolet', 'model': 'Monte Carlo'},
        {'make': 'Chevrolet', 'model': 'Prizm'},
        {'make': 'Chevrolet', 'model': 'S10 Crew Cab'},
        {'make': 'Chevrolet', 'model': 'S10 Extended Cab'},
        {'make': 'Chevrolet', 'model': 'S10 Regular Cab'},
        {'make': 'Chevrolet', 'model': 'SS'},
        {'make': 'Chevrolet', 'model': 'SSR'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 1500 Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 1500 Extended Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 1500 HD Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 1500 Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 2500 HD Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 2500 HD Extended Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 2500 HD Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 3500 Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 3500 Extended Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado (Classic) 3500 Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 1500 Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 1500 Double Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 1500 Extended Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 1500 HD Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 1500 LD Double Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 1500 Limited Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 1500 Limited Double Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 1500 Limited Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 1500 Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 2500 Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 2500 Extended Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 2500 HD Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 2500 HD Double Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 2500 HD Extended Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 2500 HD Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 2500 Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 3500 Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 3500 Extended Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 3500 HD Crew Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 3500 HD Double Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 3500 HD Extended Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 3500 HD Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Silverado 3500 Regular Cab'},
        {'make': 'Chevrolet', 'model': 'Sonic'},
        {'make': 'Chevrolet', 'model': 'Spark EV'},
        {'make': 'Chevrolet', 'model': 'Spark'},
        {'make': 'Chevrolet', 'model': 'Suburban 1500'},
        {'make': 'Chevrolet', 'model': 'Suburban 2500'},
        {'make': 'Chevrolet', 'model': 'Suburban 3500HD'},
        {'make': 'Chevrolet', 'model': 'Suburban'},
        {'make': 'Chevrolet', 'model': 'Tahoe (New)'},
        {'make': 'Chevrolet', 'model': 'Tahoe'},
        {'make': 'Chevrolet', 'model': 'Tracker'},
        {'make': 'Chevrolet', 'model': 'TrailBlazer'},
        {'make': 'Chevrolet', 'model': 'Traverse'},
        {'make': 'Chevrolet', 'model': 'Trax'},
        {'make': 'Chevrolet', 'model': 'Uplander Cargo'},
        {'make': 'Chevrolet', 'model': 'Uplander Passenger'},
        {'make': 'Chevrolet', 'model': 'Venture Cargo'},
        {'make': 'Chevrolet', 'model': 'Venture Passenger'},
        {'make': 'Chevrolet', 'model': 'Volt'},
        {'make': 'Chrysler', 'model': '200'},
        {'make': 'Chrysler', 'model': '300'},
        {'make': 'Chrysler', 'model': '300M'},
        {'make': 'Chrysler', 'model': 'Aspen'},
        {'make': 'Chrysler', 'model': 'Cirrus'},
        {'make': 'Chrysler', 'model': 'Concorde'},
        {'make': 'Chrysler', 'model': 'Crossfire'},
        {'make': 'Chrysler', 'model': 'Grand Voyager'},
        {'make': 'Chrysler', 'model': 'LHS'},
        {'make': 'Chrysler', 'model': 'PT Cruiser'},
        {'make': 'Chrysler', 'model': 'Pacifica Hybrid'},
        {'make': 'Chrysler', 'model': 'Pacifica'},
        {'make': 'Chrysler', 'model': 'Prowler'},
        {'make': 'Chrysler', 'model': 'Sebring'},
        {'make': 'Chrysler', 'model': 'Town & Country'},
        {'make': 'Chrysler', 'model': 'Voyager'},
        {'make': 'Daewoo', 'model': 'Lanos'},
        {'make': 'Daewoo', 'model': 'Leganza'},
        {'make': 'Daewoo', 'model': 'Nubira'},
        {'make': 'Dodge', 'model': 'Avenger'},
        {'make': 'Dodge', 'model': 'Caliber'},
        {'make': 'Dodge', 'model': 'Caravan Cargo'},
        {'make': 'Dodge', 'model': 'Caravan Passenger'},
        {'make': 'Dodge', 'model': 'Challenger'},
        {'make': 'Dodge', 'model': 'Charger'},
        {'make': 'Dodge', 'model': 'Dakota Club Cab'},
        {'make': 'Dodge', 'model': 'Dakota Crew Cab'},
        {'make': 'Dodge', 'model': 'Dakota Extended Cab'},
        {'make': 'Dodge', 'model': 'Dakota Quad Cab'},
        {'make': 'Dodge', 'model': 'Dakota Regular Cab'},
        {'make': 'Dodge', 'model': 'Dart'},
        {'make': 'Dodge', 'model': 'Durango'},
        {'make': 'Dodge', 'model': 'Grand Caravan Cargo'},
        {'make': 'Dodge', 'model': 'Grand Caravan Passenger'},
        {'make': 'Dodge', 'model': 'Hornet'},
        {'make': 'Dodge', 'model': 'Intrepid'},
        {'make': 'Dodge', 'model': 'Journey'},
        {'make': 'Dodge', 'model': 'Magnum'},
        {'make': 'Dodge', 'model': 'Neon'},
        {'make': 'Dodge', 'model': 'Nitro'},
        {'make': 'Dodge', 'model': 'Ram 1500 Club Cab'},
        {'make': 'Dodge', 'model': 'Ram 1500 Crew Cab'},
        {'make': 'Dodge', 'model': 'Ram 1500 Mega Cab'},
        {'make': 'Dodge', 'model': 'Ram 1500 Quad Cab'},
        {'make': 'Dodge', 'model': 'Ram 1500 Regular Cab'},
        {'make': 'Dodge', 'model': 'Ram 2500 Crew Cab'},
        {'make': 'Dodge', 'model': 'Ram 2500 Mega Cab'},
        {'make': 'Dodge', 'model': 'Ram 2500 Quad Cab'},
        {'make': 'Dodge', 'model': 'Ram 2500 Regular Cab'},
        {'make': 'Dodge', 'model': 'Ram 3500 Crew Cab'},
        {'make': 'Dodge', 'model': 'Ram 3500 Mega Cab'},
        {'make': 'Dodge', 'model': 'Ram 3500 Quad Cab'},
        {'make': 'Dodge', 'model': 'Ram 3500 Regular Cab'},
        {'make': 'Dodge', 'model': 'Ram Van 1500'},
        {'make': 'Dodge', 'model': 'Ram Van 2500'},
        {'make': 'Dodge', 'model': 'Ram Van 3500'},
        {'make': 'Dodge', 'model': 'Ram Wagon 1500'},
        {'make': 'Dodge', 'model': 'Ram Wagon 2500'},
        {'make': 'Dodge', 'model': 'Ram Wagon 3500'},
        {'make': 'Dodge', 'model': 'Sprinter 2500 Cargo'},
        {'make': 'Dodge', 'model': 'Sprinter 2500 Passenger'},
        {'make': 'Dodge', 'model': 'Sprinter 3500 Cargo'},
        {'make': 'Dodge', 'model': 'Stratus'},
        {'make': 'Dodge', 'model': 'Viper'},
        {'make': 'FIAT', 'model': '124 Spider'},
        {'make': 'FIAT', 'model': '500 Abarth'},
        {'make': 'FIAT', 'model': '500'},
        {'make': 'FIAT', 'model': '500L'},
        {'make': 'FIAT', 'model': '500X'},
        {'make': 'FIAT', 'model': '500c Abarth'},
        {'make': 'FIAT', 'model': '500c'},
        {'make': 'FIAT', 'model': '500e'},
        {'make': 'Ferrari', 'model': '296 GTB'},
        {'make': 'Ferrari', 'model': '430 Scuderia'},
        {'make': 'Ferrari', 'model': '458 Italia'},
        {'make': 'Ferrari', 'model': '458 Speciale'},
        {'make': 'Ferrari', 'model': '458 Spider'},
        {'make': 'Ferrari', 'model': '488 GTB'},
        {'make': 'Ferrari', 'model': '488 Pista'},
        {'make': 'Ferrari', 'model': '488 Spider'},
        {'make': 'Ferrari', 'model': '599 GTB Fiorano'},
        {'make': 'Ferrari', 'model': '599 GTO'},
        {'make': 'Ferrari', 'model': '612 Scaglietti'},
        {'make': 'Ferrari', 'model': '812 Competizione A'},
        {'make': 'Ferrari', 'model': '812 Competizione'},
        {'make': 'Ferrari', 'model': '812 GTS'},
        {'make': 'Ferrari', 'model': '812 Superfast'},
        {'make': 'Ferrari', 'model': 'California'},
        {'make': 'Ferrari', 'model': 'F12berlinetta'},
        {'make': 'Ferrari', 'model': 'F430'},
        {'make': 'Ferrari', 'model': 'F8'},
        {'make': 'Ferrari', 'model': 'FF'},
        {'make': 'Ferrari', 'model': 'GTC4Lusso'},
        {'make': 'Ferrari', 'model': 'Portofino'},
        {'make': 'Ferrari', 'model': 'Roma'},
        {'make': 'Ferrari', 'model': 'SF90'},
        {'make': 'Fisker', 'model': 'Karma'},
        {'make': 'Ford', 'model': 'Bronco Sport'},
        {'make': 'Ford', 'model': 'Bronco'},
        {'make': 'Ford', 'model': 'C-MAX Energi'},
        {'make': 'Ford', 'model': 'C-MAX Hybrid'},
        {'make': 'Ford', 'model': 'Contour'},
        {'make': 'Ford', 'model': 'Crown Victoria'},
        {'make': 'Ford', 'model': 'E-Transit 350 Cargo Van'},
        {'make': 'Ford', 'model': 'E150 Cargo'},
        {'make': 'Ford', 'model': 'E150 Passenger'},
        {'make': 'Ford', 'model': 'E150 Super Duty Cargo'},
        {'make': 'Ford', 'model': 'E150 Super Duty Passenger'},
        {'make': 'Ford', 'model': 'E250 Cargo'},
        {'make': 'Ford', 'model': 'E250 Super Duty Cargo'},
        {'make': 'Ford', 'model': 'E350 Super Duty Cargo'},
        {'make': 'Ford', 'model': 'E350 Super Duty Passenger'},
        {'make': 'Ford', 'model': 'EcoSport'},
        {'make': 'Ford', 'model': 'Econoline E150 Cargo'},
        {'make': 'Ford', 'model': 'Econoline E150 Passenger'},
        {'make': 'Ford', 'model': 'Econoline E250 Cargo'},
        {'make': 'Ford', 'model': 'Econoline E350 Super Duty Cargo'},
        {'make': 'Ford', 'model': 'Econoline E350 Super Duty Passenger'},
        {'make': 'Ford', 'model': 'Edge'},
        {'make': 'Ford', 'model': 'Escape Plug-in Hybrid'},
        {'make': 'Ford', 'model': 'Escape'},
        {'make': 'Ford', 'model': 'Escort'},
        {'make': 'Ford', 'model': 'Excursion'},
        {'make': 'Ford', 'model': 'Expedition EL'},
        {'make': 'Ford', 'model': 'Expedition MAX'},
        {'make': 'Ford', 'model': 'Expedition'},
        {'make': 'Ford', 'model': 'Explorer Sport Trac'},
        {'make': 'Ford', 'model': 'Explorer Sport'},
        {'make': 'Ford', 'model': 'Explorer'},
        {'make': 'Ford', 'model': 'F150 (Heritage) Regular Cab'},
        {'make': 'Ford', 'model': 'F150 (Heritage) Super Cab'},
        {'make': 'Ford', 'model': 'F150 Lightning'},
        {'make': 'Ford', 'model': 'F150 Regular Cab'},
        {'make': 'Ford', 'model': 'F150 Super Cab'},
        {'make': 'Ford', 'model': 'F150 SuperCrew Cab'},
        {'make': 'Ford', 'model': 'F250 Super Duty Crew Cab'},
        {'make': 'Ford', 'model': 'F250 Super Duty Regular Cab'},
        {'make': 'Ford', 'model': 'F250 Super Duty Super Cab'},
        {'make': 'Ford', 'model': 'F350 Super Duty Crew Cab'},
        {'make': 'Ford', 'model': 'F350 Super Duty Regular Cab'},
        {'make': 'Ford', 'model': 'F350 Super Duty Super Cab'},
        {'make': 'Ford', 'model': 'F450 Super Duty Crew Cab'},
        {'make': 'Ford', 'model': 'F450 Super Duty Regular Cab'},
        {'make': 'Ford', 'model': 'Fiesta'},
        {'make': 'Ford', 'model': 'Five Hundred'},
        {'make': 'Ford', 'model': 'Flex'},
        {'make': 'Ford', 'model': 'Focus ST'},
        {'make': 'Ford', 'model': 'Focus'},
        {'make': 'Ford', 'model': 'Freestar Cargo'},
        {'make': 'Ford', 'model': 'Freestar Passenger'},
        {'make': 'Ford', 'model': 'Freestyle'},
        {'make': 'Ford', 'model': 'Fusion Energi'},
        {'make': 'Ford', 'model': 'Fusion Plug-in Hybrid'},
        {'make': 'Ford', 'model': 'Fusion'},
        {'make': 'Ford', 'model': 'GT'},
        {'make': 'Ford', 'model': 'Maverick'},
        {'make': 'Ford', 'model': 'Mustang MACH-E'},
        {'make': 'Ford', 'model': 'Mustang'},
        {'make': 'Ford', 'model': 'Ranger Regular Cab'},
        {'make': 'Ford', 'model': 'Ranger Super Cab'},
        {'make': 'Ford', 'model': 'Ranger SuperCab'},
        {'make': 'Ford', 'model': 'Ranger SuperCrew'},
        {'make': 'Ford', 'model': 'Taurus X'},
        {'make': 'Ford', 'model': 'Taurus'},
        {'make': 'Ford', 'model': 'Thunderbird'},
        {'make': 'Ford', 'model': 'Transit 150 Cargo Van'},
        {'make': 'Ford', 'model': 'Transit 150 Crew Van'},
        {'make': 'Ford', 'model': 'Transit 150 Passenger Van'},
        {'make': 'Ford', 'model': 'Transit 150 Van'},
        {'make': 'Ford', 'model': 'Transit 150 Wagon'},
        {'make': 'Ford', 'model': 'Transit 250 Cargo Van'},
        {'make': 'Ford', 'model': 'Transit 250 Crew Van'},
        {'make': 'Ford', 'model': 'Transit 250 Van'},
        {'make': 'Ford', 'model': 'Transit 350 Cargo Van'},
        {'make': 'Ford', 'model': 'Transit 350 Crew Van'},
        {'make': 'Ford', 'model': 'Transit 350 HD Cargo Van'},
        {'make': 'Ford', 'model': 'Transit 350 HD Crew Van'},
        {'make': 'Ford', 'model': 'Transit 350 HD Van'},
        {'make': 'Ford', 'model': 'Transit 350 Passenger Van'},
        {'make': 'Ford', 'model': 'Transit 350 Van'},
        {'make': 'Ford', 'model': 'Transit 350 Wagon'},
        {'make': 'Ford', 'model': 'Transit Connect Cargo Van'},
        {'make': 'Ford', 'model': 'Transit Connect Cargo'},
        {'make': 'Ford', 'model': 'Transit Connect Passenger Wagon'},
        {'make': 'Ford', 'model': 'Transit Connect Passenger'},
        {'make': 'Ford', 'model': 'Windstar Cargo'},
        {'make': 'Ford', 'model': 'Windstar Passenger'},
        {'make': 'Ford', 'model': 'ZX2'},
        {'make': 'Freightliner', 'model': 'Sprinter 1500 Cargo'},
        {'make': 'Freightliner', 'model': 'Sprinter 1500 Passenger'},
        {'make': 'Freightliner', 'model': 'Sprinter 2500 Cargo'},
        {'make': 'Freightliner', 'model': 'Sprinter 2500 Crew'},
        {'make': 'Freightliner', 'model': 'Sprinter 2500 Passenger'},
        {'make': 'Freightliner', 'model': 'Sprinter 3500 Cargo'},
        {'make': 'Freightliner', 'model': 'Sprinter 3500 Crew'},
        {'make': 'Freightliner', 'model': 'Sprinter 3500 XD Crew'},
        {'make': 'Freightliner', 'model': 'Sprinter 3500XD Cargo'},
        {'make': 'Freightliner', 'model': 'Sprinter 4500 Cargo'},
        {'make': 'Freightliner', 'model': 'Sprinter 4500 Crew'},
        {'make': 'Freightliner', 'model': 'Sprinter WORKER Cargo'},
        {'make': 'Freightliner', 'model': 'Sprinter WORKER Passenger'},
        {'make': 'GMC', 'model': 'Acadia Limited'},
        {'make': 'GMC', 'model': 'Acadia'},
        {'make': 'GMC', 'model': 'Canyon Crew Cab'},
        {'make': 'GMC', 'model': 'Canyon Extended Cab'},
        {'make': 'GMC', 'model': 'Canyon Regular Cab'},
        {'make': 'GMC', 'model': 'Envoy XL'},
        {'make': 'GMC', 'model': 'Envoy XUV'},
        {'make': 'GMC', 'model': 'Envoy'},
        {'make': 'GMC', 'model': 'Hummer EV Pickup'},
        {'make': 'GMC', 'model': 'Jimmy'},
        {'make': 'GMC', 'model': 'Safari Cargo'},
        {'make': 'GMC', 'model': 'Safari Passenger'},
        {'make': 'GMC', 'model': 'Savana 1500 Cargo'},
        {'make': 'GMC', 'model': 'Savana 1500 Passenger'},
        {'make': 'GMC', 'model': 'Savana 2500 Cargo'},
        {'make': 'GMC', 'model': 'Savana 2500 Passenger'},
        {'make': 'GMC', 'model': 'Savana 3500 Cargo'},
        {'make': 'GMC', 'model': 'Savana 3500 Passenger'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 1500 Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 1500 Extended Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 1500 HD Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 1500 Regular Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 2500 Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 2500 HD Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 2500 HD Extended Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 2500 HD Regular Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 3500 Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 3500 Extended Cab'},
        {'make': 'GMC', 'model': 'Sierra (Classic) 3500 Regular Cab'},
        {'make': 'GMC', 'model': 'Sierra 1500 Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra 1500 Double Cab'},
        {'make': 'GMC', 'model': 'Sierra 1500 Extended Cab'},
        {'make': 'GMC', 'model': 'Sierra 1500 HD Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra 1500 Limited Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra 1500 Limited Double Cab'},
        {'make': 'GMC', 'model': 'Sierra 1500 Limited Regular Cab'},
        {'make': 'GMC', 'model': 'Sierra 1500 Regular Cab'},
        {'make': 'GMC', 'model': 'Sierra 2500 Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra 2500 Extended Cab'},
        {'make': 'GMC', 'model': 'Sierra 2500 HD Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra 2500 HD Double Cab'},
        {'make': 'GMC', 'model': 'Sierra 2500 HD Extended Cab'},
        {'make': 'GMC', 'model': 'Sierra 2500 HD Regular Cab'},
        {'make': 'GMC', 'model': 'Sierra 2500 Regular Cab'},
        {'make': 'GMC', 'model': 'Sierra 3500 Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra 3500 Extended Cab'},
        {'make': 'GMC', 'model': 'Sierra 3500 HD Crew Cab'},
        {'make': 'GMC', 'model': 'Sierra 3500 HD Double Cab'},
        {'make': 'GMC', 'model': 'Sierra 3500 HD Extended Cab'},
        {'make': 'GMC', 'model': 'Sierra 3500 HD Regular Cab'},
        {'make': 'GMC', 'model': 'Sierra 3500 Regular Cab'},
        {'make': 'GMC', 'model': 'Sonoma Crew Cab'},
        {'make': 'GMC', 'model': 'Sonoma Extended Cab'},
        {'make': 'GMC', 'model': 'Sonoma Regular Cab'},
        {'make': 'GMC', 'model': 'Terrain'},
        {'make': 'GMC', 'model': 'Yukon Denali'},
        {'make': 'GMC', 'model': 'Yukon XL 1500'},
        {'make': 'GMC', 'model': 'Yukon XL 2500'},
        {'make': 'GMC', 'model': 'Yukon XL'},
        {'make': 'GMC', 'model': 'Yukon'},
        {'make': 'Genesis', 'model': 'Electrified G80'},
        {'make': 'Genesis', 'model': 'G70'},
        {'make': 'Genesis', 'model': 'G80'},
        {'make': 'Genesis', 'model': 'G90'},
        {'make': 'Genesis', 'model': 'GV60'},
        {'make': 'Genesis', 'model': 'GV70'},
        {'make': 'Genesis', 'model': 'GV80'},
        {'make': 'HUMMER', 'model': 'H1'},
        {'make': 'HUMMER', 'model': 'H2'},
        {'make': 'HUMMER', 'model': 'H3'},
        {'make': 'HUMMER', 'model': 'H3T'},
        {'make': 'Honda', 'model': 'Accord Crosstour'},
        {'make': 'Honda', 'model': 'Accord Hybrid'},
        {'make': 'Honda', 'model': 'Accord'},
        {'make': 'Honda', 'model': 'CR-V Hybrid'},
        {'make': 'Honda', 'model': 'CR-V'},
        {'make': 'Honda', 'model': 'CR-Z'},
        {'make': 'Honda', 'model': 'Civic Type R'},
        {'make': 'Honda', 'model': 'Civic'},
        {'make': 'Honda', 'model': 'Clarity Electric'},
        {'make': 'Honda', 'model': 'Clarity Fuel Cell'},
        {'make': 'Honda', 'model': 'Clarity Plug-in Hybrid'},
        {'make': 'Honda', 'model': 'Crosstour'},
        {'make': 'Honda', 'model': 'Element'},
        {'make': 'Honda', 'model': 'Fit'},
        {'make': 'Honda', 'model': 'HR-V'},
        {'make': 'Honda', 'model': 'Insight'},
        {'make': 'Honda', 'model': 'Odyssey'},
        {'make': 'Honda', 'model': 'Passport'},
        {'make': 'Honda', 'model': 'Pilot'},
        {'make': 'Honda', 'model': 'Prelude'},
        {'make': 'Honda', 'model': 'Ridgeline'},
        {'make': 'Honda', 'model': 'S2000'},
        {'make': 'Hyundai', 'model': 'Accent'},
        {'make': 'Hyundai', 'model': 'Azera'},
        {'make': 'Hyundai', 'model': 'Elantra GT'},
        {'make': 'Hyundai', 'model': 'Elantra Hybrid'},
        {'make': 'Hyundai', 'model': 'Elantra N'},
        {'make': 'Hyundai', 'model': 'Elantra'},
        {'make': 'Hyundai', 'model': 'Entourage'},
        {'make': 'Hyundai', 'model': 'Equus'},
        {'make': 'Hyundai', 'model': 'Genesis Coupe'},
        {'make': 'Hyundai', 'model': 'Genesis'},
        {'make': 'Hyundai', 'model': 'IONIQ 5'},
        {'make': 'Hyundai', 'model': 'Ioniq Electric'},
        {'make': 'Hyundai', 'model': 'Ioniq Hybrid'},
        {'make': 'Hyundai', 'model': 'Ioniq Plug-in Hybrid'},
        {'make': 'Hyundai', 'model': 'Kona Electric'},
        {'make': 'Hyundai', 'model': 'Kona N'},
        {'make': 'Hyundai', 'model': 'Kona'},
        {'make': 'Hyundai', 'model': 'NEXO'},
        {'make': 'Hyundai', 'model': 'Palisade'},
        {'make': 'Hyundai', 'model': 'Santa Cruz'},
        {'make': 'Hyundai', 'model': 'Santa Fe Hybrid'},
        {'make': 'Hyundai', 'model': 'Santa Fe Plug-in Hybrid'},
        {'make': 'Hyundai', 'model': 'Santa Fe Sport'},
        {'make': 'Hyundai', 'model': 'Santa Fe XL'},
        {'make': 'Hyundai', 'model': 'Santa Fe'},
        {'make': 'Hyundai', 'model': 'Sonata Hybrid'},
        {'make': 'Hyundai', 'model': 'Sonata Plug-in Hybrid'},
        {'make': 'Hyundai', 'model': 'Sonata'},
        {'make': 'Hyundai', 'model': 'Tiburon'},
        {'make': 'Hyundai', 'model': 'Tucson Fuel Cell'},
        {'make': 'Hyundai', 'model': 'Tucson Hybrid'},
        {'make': 'Hyundai', 'model': 'Tucson Plug-in Hybrid'},
        {'make': 'Hyundai', 'model': 'Tucson'},
        {'make': 'Hyundai', 'model': 'Veloster'},
        {'make': 'Hyundai', 'model': 'Venue'},
        {'make': 'Hyundai', 'model': 'Veracruz'},
        {'make': 'Hyundai', 'model': 'XG300'},
        {'make': 'Hyundai', 'model': 'XG350'},
        {'make': 'INFINITI', 'model': 'EX'},
        {'make': 'INFINITI', 'model': 'FX'},
        {'make': 'INFINITI', 'model': 'G'},
        {'make': 'INFINITI', 'model': 'I'},
        {'make': 'INFINITI', 'model': 'JX'},
        {'make': 'INFINITI', 'model': 'M'},
        {'make': 'INFINITI', 'model': 'Q'},
        {'make': 'INFINITI', 'model': 'Q40'},
        {'make': 'INFINITI', 'model': 'Q50'},
        {'make': 'INFINITI', 'model': 'Q60'},
        {'make': 'INFINITI', 'model': 'Q70'},
        {'make': 'INFINITI', 'model': 'QX'},
        {'make': 'INFINITI', 'model': 'QX30'},
        {'make': 'INFINITI', 'model': 'QX50'},
        {'make': 'INFINITI', 'model': 'QX55'},
        {'make': 'INFINITI', 'model': 'QX60'},
        {'make': 'INFINITI', 'model': 'QX70'},
        {'make': 'INFINITI', 'model': 'QX80'},
        {'make': 'Isuzu', 'model': 'Amigo'},
        {'make': 'Isuzu', 'model': 'Ascender'},
        {'make': 'Isuzu', 'model': 'Axiom'},
        {'make': 'Isuzu', 'model': 'Hombre Regular Cab'},
        {'make': 'Isuzu', 'model': 'Hombre Spacecab'},
        {'make': 'Isuzu', 'model': 'Rodeo Sport'},
        {'make': 'Isuzu', 'model': 'Rodeo'},
        {'make': 'Isuzu', 'model': 'Trooper'},
        {'make': 'Isuzu', 'model': 'VehiCROSS'},
        {'make': 'Isuzu', 'model': 'i-280 Extended Cab'},
        {'make': 'Isuzu', 'model': 'i-290 Extended Cab'},
        {'make': 'Isuzu', 'model': 'i-350 Crew Cab'},
        {'make': 'Isuzu', 'model': 'i-370 Crew Cab'},
        {'make': 'Isuzu', 'model': 'i-370 Extended Cab'},
        {'make': 'Jaguar', 'model': 'E-PACE'},
        {'make': 'Jaguar', 'model': 'F-PACE'},
        {'make': 'Jaguar', 'model': 'F-TYPE'},
        {'make': 'Jaguar', 'model': 'I-PACE'},
        {'make': 'Jaguar', 'model': 'S-Type'},
        {'make': 'Jaguar', 'model': 'X-Type'},
        {'make': 'Jaguar', 'model': 'XE'},
        {'make': 'Jaguar', 'model': 'XF'},
        {'make': 'Jaguar', 'model': 'XJ'},
        {'make': 'Jaguar', 'model': 'XK'},
        {'make': 'Jeep', 'model': 'Cherokee'},
        {'make': 'Jeep', 'model': 'Commander'},
        {'make': 'Jeep', 'model': 'Compass'},
        {'make': 'Jeep', 'model': 'Gladiator'},
        {'make': 'Jeep', 'model': 'Grand Cherokee 4xe'},
        {'make': 'Jeep', 'model': 'Grand Cherokee L'},
        {'make': 'Jeep', 'model': 'Grand Cherokee'},
        {'make': 'Jeep', 'model': 'Grand Wagoneer L'},
        {'make': 'Jeep', 'model': 'Grand Wagoneer'},
        {'make': 'Jeep', 'model': 'Liberty'},
        {'make': 'Jeep', 'model': 'Patriot'},
        {'make': 'Jeep', 'model': 'Renegade'},
        {'make': 'Jeep', 'model': 'Wagoneer L'},
        {'make': 'Jeep', 'model': 'Wagoneer'},
        {'make': 'Jeep', 'model': 'Wrangler Unlimited 4xe'},
        {'make': 'Jeep', 'model': 'Wrangler Unlimited'},
        {'make': 'Jeep', 'model': 'Wrangler'},
        {'make': 'Kia', 'model': 'Amanti'},
        {'make': 'Kia', 'model': 'Borrego'},
        {'make': 'Kia', 'model': 'Cadenza'},
        {'make': 'Kia', 'model': 'Carnival'},
        {'make': 'Kia', 'model': 'EV6'},
        {'make': 'Kia', 'model': 'Forte Koup'},
        {'make': 'Kia', 'model': 'Forte'},
        {'make': 'Kia', 'model': 'Forte5'},
        {'make': 'Kia', 'model': 'K5'},
        {'make': 'Kia', 'model': 'K900'},
        {'make': 'Kia', 'model': 'Niro EV'},
        {'make': 'Kia', 'model': 'Niro Plug-in Hybrid'},
        {'make': 'Kia', 'model': 'Niro'},
        {'make': 'Kia', 'model': 'Optima (2006.5)'},
        {'make': 'Kia', 'model': 'Optima Hybrid'},
        {'make': 'Kia', 'model': 'Optima Plug-in Hybrid'},
        {'make': 'Kia', 'model': 'Optima'},
        {'make': 'Kia', 'model': 'Rio'},
        {'make': 'Kia', 'model': 'Rondo'},
        {'make': 'Kia', 'model': 'Sedona'},
        {'make': 'Kia', 'model': 'Seltos'},
        {'make': 'Kia', 'model': 'Sephia'},
        {'make': 'Kia', 'model': 'Sorento Hybrid'},
        {'make': 'Kia', 'model': 'Sorento Plug-in Hybrid'},
        {'make': 'Kia', 'model': 'Sorento'},
        {'make': 'Kia', 'model': 'Soul EV'},
        {'make': 'Kia', 'model': 'Soul'},
        {'make': 'Kia', 'model': 'Spectra'},
        {'make': 'Kia', 'model': 'Sportage Hybrid'},
        {'make': 'Kia', 'model': 'Sportage Plug-in Hybrid'},
        {'make': 'Kia', 'model': 'Sportage'},
        {'make': 'Kia', 'model': 'Stinger'},
        {'make': 'Kia', 'model': 'Telluride'},
        {'make': 'Lamborghini', 'model': 'Aventador'},
        {'make': 'Lamborghini', 'model': 'Gallardo'},
        {'make': 'Lamborghini', 'model': 'Huracan'},
        {'make': 'Lamborghini', 'model': 'Murcielago LP640'},
        {'make': 'Lamborghini', 'model': 'Murcielago'},
        {'make': 'Lamborghini', 'model': 'Urus'},
        {'make': 'Land Rover', 'model': 'Defender 110'},
        {'make': 'Land Rover', 'model': 'Defender 130'},
        {'make': 'Land Rover', 'model': 'Defender 90'},
        {'make': 'Land Rover', 'model': 'Discovery Series II'},
        {'make': 'Land Rover', 'model': 'Discovery Sport'},
        {'make': 'Land Rover', 'model': 'Discovery'},
        {'make': 'Land Rover', 'model': 'Freelander'},
        {'make': 'Land Rover', 'model': 'LR2'},
        {'make': 'Land Rover', 'model': 'LR3'},
        {'make': 'Land Rover', 'model': 'LR4'},
        {'make': 'Land Rover', 'model': 'Range Rover Evoque'},
        {'make': 'Land Rover', 'model': 'Range Rover Sport'},
        {'make': 'Land Rover', 'model': 'Range Rover Velar'},
        {'make': 'Land Rover', 'model': 'Range Rover'},
        {'make': 'Lexus', 'model': 'CT'},
        {'make': 'Lexus', 'model': 'ES'},
        {'make': 'Lexus', 'model': 'GS'},
        {'make': 'Lexus', 'model': 'GX'},
        {'make': 'Lexus', 'model': 'HS'},
        {'make': 'Lexus', 'model': 'IS F'},
        {'make': 'Lexus', 'model': 'IS'},
        {'make': 'Lexus', 'model': 'LC'},
        {'make': 'Lexus', 'model': 'LFA'},
        {'make': 'Lexus', 'model': 'LS'},
        {'make': 'Lexus', 'model': 'LX'},
        {'make': 'Lexus', 'model': 'NX'},
        {'make': 'Lexus', 'model': 'RC'},
        {'make': 'Lexus', 'model': 'RX'},
        {'make': 'Lexus', 'model': 'RZ'},
        {'make': 'Lexus', 'model': 'SC'},
        {'make': 'Lexus', 'model': 'TX'},
        {'make': 'Lexus', 'model': 'UX'},
        {'make': 'Lincoln', 'model': 'Aviator'},
        {'make': 'Lincoln', 'model': 'Blackwood'},
        {'make': 'Lincoln', 'model': 'Continental'},
        {'make': 'Lincoln', 'model': 'Corsair'},
        {'make': 'Lincoln', 'model': 'LS'},
        {'make': 'Lincoln', 'model': 'MKC'},
        {'make': 'Lincoln', 'model': 'MKS'},
        {'make': 'Lincoln', 'model': 'MKT'},
        {'make': 'Lincoln', 'model': 'MKX'},
        {'make': 'Lincoln', 'model': 'MKZ'},
        {'make': 'Lincoln', 'model': 'Mark LT'},
        {'make': 'Lincoln', 'model': 'Nautilus'},
        {'make': 'Lincoln', 'model': 'Navigator L'},
        {'make': 'Lincoln', 'model': 'Navigator'},
        {'make': 'Lincoln', 'model': 'Town Car'},
        {'make': 'Lincoln', 'model': 'Zephyr'},
        {'make': 'Lotus', 'model': 'Elise'},
        {'make': 'Lotus', 'model': 'Evora 400'},
        {'make': 'Lotus', 'model': 'Evora GT'},
        {'make': 'Lotus', 'model': 'Evora'},
        {'make': 'Lotus', 'model': 'Exige S'},
        {'make': 'Lotus', 'model': 'Exige'},
        {'make': 'Lucid', 'model': 'Air'},
        {'make': 'MAZDA', 'model': '626'},
        {'make': 'MAZDA', 'model': 'B-Series Cab Plus'},
        {'make': 'MAZDA', 'model': 'B-Series Extended Cab'},
        {'make': 'MAZDA', 'model': 'B-Series Regular Cab'},
        {'make': 'MAZDA', 'model': 'CX-3'},
        {'make': 'MAZDA', 'model': 'CX-30'},
        {'make': 'MAZDA', 'model': 'CX-5'},
        {'make': 'MAZDA', 'model': 'CX-50'},
        {'make': 'MAZDA', 'model': 'CX-7'},
        {'make': 'MAZDA', 'model': 'CX-9'},
        {'make': 'MAZDA', 'model': 'CX-90'},
        {'make': 'MAZDA', 'model': 'MAZDA2'},
        {'make': 'MAZDA', 'model': 'MAZDA3'},
        {'make': 'MAZDA', 'model': 'MAZDA5'},
        {'make': 'MAZDA', 'model': 'MAZDA6'},
        {'make': 'MAZDA', 'model': 'MPV'},
        {'make': 'MAZDA', 'model': 'MX-30'},
        {'make': 'MAZDA', 'model': 'MX-5 Miata RF'},
        {'make': 'MAZDA', 'model': 'MX-5 Miata'},
        {'make': 'MAZDA', 'model': 'Millenia'},
        {'make': 'MAZDA', 'model': 'Protege'},
        {'make': 'MAZDA', 'model': 'Protege5'},
        {'make': 'MAZDA', 'model': 'RX-8'},
        {'make': 'MAZDA', 'model': 'Tribute'},
        {'make': 'MINI', 'model': 'Clubman'},
        {'make': 'MINI', 'model': 'Convertible'},
        {'make': 'MINI', 'model': 'Cooper'},
        {'make': 'MINI', 'model': 'Countryman'},
        {'make': 'MINI', 'model': 'Coupe'},
        {'make': 'MINI', 'model': 'Hardtop 2 Door'},
        {'make': 'MINI', 'model': 'Hardtop 4 Door'},
        {'make': 'MINI', 'model': 'Hardtop'},
        {'make': 'MINI', 'model': 'Paceman'},
        {'make': 'MINI', 'model': 'Roadster'},
        {'make': 'Maserati', 'model': 'Coupe'},
        {'make': 'Maserati', 'model': 'Ghibli'},
        {'make': 'Maserati', 'model': 'GranSport'},
        {'make': 'Maserati', 'model': 'GranTurismo'},
        {'make': 'Maserati', 'model': 'Grecale'},
        {'make': 'Maserati', 'model': 'Levante'},
        {'make': 'Maserati', 'model': 'MC20'},
        {'make': 'Maserati', 'model': 'Quattroporte'},
        {'make': 'Maybach', 'model': '57'},
        {'make': 'Maybach', 'model': '62'},
        {'make': 'McLaren', 'model': '570GT'},
        {'make': 'McLaren', 'model': '570S'},
        {'make': 'McLaren', 'model': '600LT'},
        {'make': 'McLaren', 'model': '650S'},
        {'make': 'McLaren', 'model': '675LT'},
        {'make': 'McLaren', 'model': '720S'},
        {'make': 'McLaren', 'model': 'MP4-12C'},
        {'make': 'Mercedes-Benz', 'model': 'A-Class'},
        {'make': 'Mercedes-Benz', 'model': 'B-Class'},
        {'make': 'Mercedes-Benz', 'model': 'C-Class'},
        {'make': 'Mercedes-Benz', 'model': 'CL-Class'},
        {'make': 'Mercedes-Benz', 'model': 'CLA'},
        {'make': 'Mercedes-Benz', 'model': 'CLA-Class'},
        {'make': 'Mercedes-Benz', 'model': 'CLK-Class'},
        {'make': 'Mercedes-Benz', 'model': 'CLS'},
        {'make': 'Mercedes-Benz', 'model': 'CLS-Class'},
        {'make': 'Mercedes-Benz', 'model': 'E-Class'},
        {'make': 'Mercedes-Benz', 'model': 'G-Class'},
        {'make': 'Mercedes-Benz', 'model': 'GL-Class'},
        {'make': 'Mercedes-Benz', 'model': 'GLA'},
        {'make': 'Mercedes-Benz', 'model': 'GLA-Class'},
        {'make': 'Mercedes-Benz', 'model': 'GLB'},
        {'make': 'Mercedes-Benz', 'model': 'GLC Coupe'},
        {'make': 'Mercedes-Benz', 'model': 'GLC'},
        {'make': 'Mercedes-Benz', 'model': 'GLE Coupe'},
        {'make': 'Mercedes-Benz', 'model': 'GLE'},
        {'make': 'Mercedes-Benz', 'model': 'GLK-Class'},
        {'make': 'Mercedes-Benz', 'model': 'GLS'},
        {'make': 'Mercedes-Benz', 'model': 'M-Class'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG A-Class'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG C-Class'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG CLA'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG CLS'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG E-Class'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG EQS'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG G-Class'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG GLA'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG GLB'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG GLC Coupe'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG GLC'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG GLE Coupe'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG GLE'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG GLS'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG GT'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG S-Class'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG SL'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG SLC'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-AMG SLK'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-EQ EQB'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-EQ EQE SUV'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-EQ EQE'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-EQ EQS SUV'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-EQ EQS'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-Maybach GLS'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-Maybach S 600'},
        {'make': 'Mercedes-Benz', 'model': 'Mercedes-Maybach S-Class'},
        {'make': 'Mercedes-Benz', 'model': 'Metris Cargo'},
        {'make': 'Mercedes-Benz', 'model': 'Metris Passenger'},
        {'make': 'Mercedes-Benz', 'model': 'Metris WORKER Cargo'},
        {'make': 'Mercedes-Benz', 'model': 'Metris WORKER Passenger'},
        {'make': 'Mercedes-Benz', 'model': 'R-Class'},
        {'make': 'Mercedes-Benz', 'model': 'S-Class'},
        {'make': 'Mercedes-Benz', 'model': 'SL'},
        {'make': 'Mercedes-Benz', 'model': 'SL-Class'},
        {'make': 'Mercedes-Benz', 'model': 'SLC'},
        {'make': 'Mercedes-Benz', 'model': 'SLK'},
        {'make': 'Mercedes-Benz', 'model': 'SLK-Class'},
        {'make': 'Mercedes-Benz', 'model': 'SLR McLaren'},
        {'make': 'Mercedes-Benz', 'model': 'SLS-Class'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 1500 Cargo'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 1500 Passenger'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 2500 Cargo'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 2500 Crew'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 2500 Passenger'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 3500 Cargo'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 3500 Crew'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 3500 XD Cargo'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 3500 XD Crew'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 4500 Cargo'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter 4500 Crew'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter WORKER Cargo'},
        {'make': 'Mercedes-Benz', 'model': 'Sprinter WORKER Passenger'},
        {'make': 'Mercury', 'model': 'Cougar'},
        {'make': 'Mercury', 'model': 'Grand Marquis'},
        {'make': 'Mercury', 'model': 'Marauder'},
        {'make': 'Mercury', 'model': 'Mariner'},
        {'make': 'Mercury', 'model': 'Milan'},
        {'make': 'Mercury', 'model': 'Montego'},
        {'make': 'Mercury', 'model': 'Monterey'},
        {'make': 'Mercury', 'model': 'Mountaineer'},
        {'make': 'Mercury', 'model': 'Mystique'},
        {'make': 'Mercury', 'model': 'Sable'},
        {'make': 'Mercury', 'model': 'Villager'},
        {'make': 'Mitsubishi', 'model': 'Diamante'},
        {'make': 'Mitsubishi', 'model': 'Eclipse Cross'},
        {'make': 'Mitsubishi', 'model': 'Eclipse'},
        {'make': 'Mitsubishi', 'model': 'Endeavor'},
        {'make': 'Mitsubishi', 'model': 'Galant'},
        {'make': 'Mitsubishi', 'model': 'Lancer Evolution'},
        {'make': 'Mitsubishi', 'model': 'Lancer'},
        {'make': 'Mitsubishi', 'model': 'Mirage G4'},
        {'make': 'Mitsubishi', 'model': 'Mirage'},
        {'make': 'Mitsubishi', 'model': 'Montero Sport'},
        {'make': 'Mitsubishi', 'model': 'Montero'},
        {'make': 'Mitsubishi', 'model': 'Outlander PHEV'},
        {'make': 'Mitsubishi', 'model': 'Outlander Sport'},
        {'make': 'Mitsubishi', 'model': 'Outlander'},
        {'make': 'Mitsubishi', 'model': 'Raider Double Cab'},
        {'make': 'Mitsubishi', 'model': 'Raider Extended Cab'},
        {'make': 'Mitsubishi', 'model': 'i-MiEV'},
        {'make': 'Nissan', 'model': '350Z'},
        {'make': 'Nissan', 'model': '370Z'},
        {'make': 'Nissan', 'model': '400Z'},
        {'make': 'Nissan', 'model': 'Altima'},
        {'make': 'Nissan', 'model': 'Ariya'},
        {'make': 'Nissan', 'model': 'Armada'},
        {'make': 'Nissan', 'model': 'Frontier Crew Cab'},
        {'make': 'Nissan', 'model': 'Frontier King Cab'},
        {'make': 'Nissan', 'model': 'Frontier Regular Cab'},
        {'make': 'Nissan', 'model': 'GT-R'},
        {'make': 'Nissan', 'model': 'JUKE'},
        {'make': 'Nissan', 'model': 'Kicks'},
        {'make': 'Nissan', 'model': 'LEAF'},
        {'make': 'Nissan', 'model': 'Maxima'},
        {'make': 'Nissan', 'model': 'Murano'},
        {'make': 'Nissan', 'model': 'NV1500 Cargo'},
        {'make': 'Nissan', 'model': 'NV200 Taxi'},
        {'make': 'Nissan', 'model': 'NV200'},
        {'make': 'Nissan', 'model': 'NV2500 HD Cargo'},
        {'make': 'Nissan', 'model': 'NV3500 HD Cargo'},
        {'make': 'Nissan', 'model': 'NV3500 HD Passenger'},
        {'make': 'Nissan', 'model': 'Pathfinder Armada'},
        {'make': 'Nissan', 'model': 'Pathfinder'},
        {'make': 'Nissan', 'model': 'Quest'},
        {'make': 'Nissan', 'model': 'Rogue Select'},
        {'make': 'Nissan', 'model': 'Rogue Sport'},
        {'make': 'Nissan', 'model': 'Rogue'},
        {'make': 'Nissan', 'model': 'Sentra'},
        {'make': 'Nissan', 'model': 'TITAN Single Cab'},
        {'make': 'Nissan', 'model': 'TITAN XD Crew Cab'},
        {'make': 'Nissan', 'model': 'TITAN XD King Cab'},
        {'make': 'Nissan', 'model': 'TITAN XD Single Cab'},
        {'make': 'Nissan', 'model': 'Titan Crew Cab'},
        {'make': 'Nissan', 'model': 'Titan King Cab'},
        {'make': 'Nissan', 'model': 'Versa Note'},
        {'make': 'Nissan', 'model': 'Versa'},
        {'make': 'Nissan', 'model': 'Xterra'},
        {'make': 'Nissan', 'model': 'Z'},
        {'make': 'Nissan', 'model': 'cube'},
        {'make': 'Oldsmobile', 'model': 'Alero'},
        {'make': 'Oldsmobile', 'model': 'Aurora'},
        {'make': 'Oldsmobile', 'model': 'Bravada'},
        {'make': 'Oldsmobile', 'model': 'Intrigue'},
        {'make': 'Oldsmobile', 'model': 'Silhouette'},
        {'make': 'Panoz', 'model': 'Esperante'},
        {'make': 'Plymouth', 'model': 'Breeze'},
        {'make': 'Plymouth', 'model': 'Grand Voyager'},
        {'make': 'Plymouth', 'model': 'Neon'},
        {'make': 'Plymouth', 'model': 'Prowler'},
        {'make': 'Plymouth', 'model': 'Voyager'},
        {'make': 'Polestar', 'model': '1'},
        {'make': 'Polestar', 'model': '2'},
        {'make': 'Polestar', 'model': '3'},
        {'make': 'Pontiac', 'model': 'Aztek'},
        {'make': 'Pontiac', 'model': 'Bonneville'},
        {'make': 'Pontiac', 'model': 'Firebird'},
        {'make': 'Pontiac', 'model': 'G3'},
        {'make': 'Pontiac', 'model': 'G5'},
        {'make': 'Pontiac', 'model': 'G6 (2009.5)'},
        {'make': 'Pontiac', 'model': 'G6'},
        {'make': 'Pontiac', 'model': 'G8'},
        {'make': 'Pontiac', 'model': 'GTO'},
        {'make': 'Pontiac', 'model': 'Grand Am'},
        {'make': 'Pontiac', 'model': 'Grand Prix'},
        {'make': 'Pontiac', 'model': 'Montana SV6'},
        {'make': 'Pontiac', 'model': 'Montana'},
        {'make': 'Pontiac', 'model': 'Solstice'},
        {'make': 'Pontiac', 'model': 'Sunfire'},
        {'make': 'Pontiac', 'model': 'Torrent'},
        {'make': 'Pontiac', 'model': 'Vibe'},
        {'make': 'Porsche', 'model': '718 Boxster'},
        {'make': 'Porsche', 'model': '718 Cayman'},
        {'make': 'Porsche', 'model': '718 Spyder'},
        {'make': 'Porsche', 'model': '911'},
        {'make': 'Porsche', 'model': 'Boxster'},
        {'make': 'Porsche', 'model': 'Carrera GT'},
        {'make': 'Porsche', 'model': 'Cayenne Coupe'},
        {'make': 'Porsche', 'model': 'Cayenne'},
        {'make': 'Porsche', 'model': 'Cayman'},
        {'make': 'Porsche', 'model': 'Macan'},
        {'make': 'Porsche', 'model': 'Panamera'},
        {'make': 'Porsche', 'model': 'Taycan Cross Turismo'},
        {'make': 'Porsche', 'model': 'Taycan'},
        {'make': 'Ram', 'model': '1500 Classic Crew Cab'},
        {'make': 'Ram', 'model': '1500 Classic Quad Cab'},
        {'make': 'Ram', 'model': '1500 Classic Regular Cab'},
        {'make': 'Ram', 'model': '1500 Crew Cab'},
        {'make': 'Ram', 'model': '1500 Quad Cab'},
        {'make': 'Ram', 'model': '1500 Regular Cab'},
        {'make': 'Ram', 'model': '2500 Crew Cab'},
        {'make': 'Ram', 'model': '2500 Mega Cab'},
        {'make': 'Ram', 'model': '2500 Regular Cab'},
        {'make': 'Ram', 'model': '3500 Crew Cab'},
        {'make': 'Ram', 'model': '3500 Mega Cab'},
        {'make': 'Ram', 'model': '3500 Regular Cab'},
        {'make': 'Ram', 'model': 'C/V Tradesman'},
        {'make': 'Ram', 'model': 'C/V'},
        {'make': 'Ram', 'model': 'Dakota Crew Cab'},
        {'make': 'Ram', 'model': 'Dakota Extended Cab'},
        {'make': 'Ram', 'model': 'ProMaster 1500 Cargo'},
        {'make': 'Ram', 'model': 'ProMaster 2500 Cargo'},
        {'make': 'Ram', 'model': 'ProMaster 3500 Cargo'},
        {'make': 'Ram', 'model': 'ProMaster Cargo Van'},
        {'make': 'Ram', 'model': 'ProMaster City'},
        {'make': 'Ram', 'model': 'ProMaster Window Van'},
        {'make': 'Rivian', 'model': 'R1S'},
        {'make': 'Rivian', 'model': 'R1T'},
        {'make': 'Rolls-Royce', 'model': 'Cullinan'},
        {'make': 'Rolls-Royce', 'model': 'Dawn'},
        {'make': 'Rolls-Royce', 'model': 'Ghost'},
        {'make': 'Rolls-Royce', 'model': 'Phantom'},
        {'make': 'Rolls-Royce', 'model': 'Wraith'},
        {'make': 'SRT', 'model': 'Viper'},
        {'make': 'Saab', 'model': '9-2X'},
        {'make': 'Saab', 'model': '9-4X'},
        {'make': 'Saab', 'model': '9-7X'},
        {'make': 'Saab', 'model': '9.???'},
        {'make': 'Saturn', 'model': 'Astra'},
        {'make': 'Saturn', 'model': 'Aura'},
        {'make': 'Saturn', 'model': 'Ion'},
        {'make': 'Saturn', 'model': 'L-Series'},
        {'make': 'Saturn', 'model': 'Outlook'},
        {'make': 'Saturn', 'model': 'Relay'},
        {'make': 'Saturn', 'model': 'S-Series'},
        {'make': 'Saturn', 'model': 'SKY'},
        {'make': 'Saturn', 'model': 'VUE'},
        {'make': 'Scion', 'model': 'FR-S'},
        {'make': 'Scion', 'model': 'iA'},
        {'make': 'Scion', 'model': 'iM'},
        {'make': 'Scion', 'model': 'iQ'},
        {'make': 'Scion', 'model': 'tC'},
        {'make': 'Scion', 'model': 'xA'},
        {'make': 'Scion', 'model': 'xB'},
        {'make': 'Scion', 'model': 'xD'},
        {'make': 'Subaru', 'model': 'Ascent'},
        {'make': 'Subaru', 'model': 'B9 Tribeca'},
        {'make': 'Subaru', 'model': 'BRZ'},
        {'make': 'Subaru', 'model': 'Baja'},
        {'make': 'Subaru', 'model': 'Crosstrek'},
        {'make': 'Subaru', 'model': 'Forester'},
        {'make': 'Subaru', 'model': 'Impreza'},
        {'make': 'Subaru', 'model': 'Legacy'},
        {'make': 'Subaru', 'model': 'Outback'},
        {'make': 'Subaru', 'model': 'Solterra'},
        {'make': 'Subaru', 'model': 'Tribeca'},
        {'make': 'Subaru', 'model': 'WRX'},
        {'make': 'Subaru', 'model': 'XV Crosstrek'},
        {'make': 'Suzuki', 'model': 'Aerio'},
        {'make': 'Suzuki', 'model': 'Equator Crew Cab'},
        {'make': 'Suzuki', 'model': 'Equator Extended Cab'},
        {'make': 'Suzuki', 'model': 'Esteem'},
        {'make': 'Suzuki', 'model': 'Forenza'},
        {'make': 'Suzuki', 'model': 'Grand Vitara'},
        {'make': 'Suzuki', 'model': 'Kizashi'},
        {'make': 'Suzuki', 'model': 'Reno'},
        {'make': 'Suzuki', 'model': 'SX4'},
        {'make': 'Suzuki', 'model': 'Swift'},
        {'make': 'Suzuki', 'model': 'Verona'},
        {'make': 'Suzuki', 'model': 'Vitara'},
        {'make': 'Suzuki', 'model': 'XL-7'},
        {'make': 'Suzuki', 'model': 'XL7'},
        {'make': 'Tesla', 'model': 'Cybertruck'},
        {'make': 'Tesla', 'model': 'Model 3'},
        {'make': 'Tesla', 'model': 'Model S'},
        {'make': 'Tesla', 'model': 'Model X'},
        {'make': 'Tesla', 'model': 'Model Y'},
        {'make': 'Toyota', 'model': '4Runner'},
        {'make': 'Toyota', 'model': '86'},
        {'make': 'Toyota', 'model': 'Avalon Hybrid'},
        {'make': 'Toyota', 'model': 'Avalon'},
        {'make': 'Toyota', 'model': 'C-HR'},
        {'make': 'Toyota', 'model': 'Camry Hybrid'},
        {'make': 'Toyota', 'model': 'Camry'},
        {'make': 'Toyota', 'model': 'Celica'},
        {'make': 'Toyota', 'model': 'Corolla Cross Hybrid'},
        {'make': 'Toyota', 'model': 'Corolla Cross'},
        {'make': 'Toyota', 'model': 'Corolla Hatchback'},
        {'make': 'Toyota', 'model': 'Corolla Hybrid'},
        {'make': 'Toyota', 'model': 'Corolla iM'},
        {'make': 'Toyota', 'model': 'Corolla'},
        {'make': 'Toyota', 'model': 'Crown'},
        {'make': 'Toyota', 'model': 'Echo'},
        {'make': 'Toyota', 'model': 'FJ Cruiser'},
        {'make': 'Toyota', 'model': 'GR Supra'},
        {'make': 'Toyota', 'model': 'GR86'},
        {'make': 'Toyota', 'model': 'Highlander Hybrid'},
        {'make': 'Toyota', 'model': 'Highlander'},
        {'make': 'Toyota', 'model': 'Land Cruiser'},
        {'make': 'Toyota', 'model': 'MR2'},
        {'make': 'Toyota', 'model': 'Matrix'},
        {'make': 'Toyota', 'model': 'Mirai'},
        {'make': 'Toyota', 'model': 'Prius Plug-in Hybrid'},
        {'make': 'Toyota', 'model': 'Prius Prime'},
        {'make': 'Toyota', 'model': 'Prius c'},
        {'make': 'Toyota', 'model': 'Prius v'},
        {'make': 'Toyota', 'model': 'Prius'},
        {'make': 'Toyota', 'model': 'RAV4 Hybrid'},
        {'make': 'Toyota', 'model': 'RAV4 Prime'},
        {'make': 'Toyota', 'model': 'RAV4'},
        {'make': 'Toyota', 'model': 'Sequoia'},
        {'make': 'Toyota', 'model': 'Sienna'},
        {'make': 'Toyota', 'model': 'Solara'},
        {'make': 'Toyota', 'model': 'Tacoma Access Cab'},
        {'make': 'Toyota', 'model': 'Tacoma Double Cab'},
        {'make': 'Toyota', 'model': 'Tacoma Regular Cab'},
        {'make': 'Toyota', 'model': 'Tacoma Xtracab'},
        {'make': 'Toyota', 'model': 'Tundra Access Cab'},
        {'make': 'Toyota', 'model': 'Tundra CrewMax'},
        {'make': 'Toyota', 'model': 'Tundra Double Cab'},
        {'make': 'Toyota', 'model': 'Tundra Hybrid CrewMax'},
        {'make': 'Toyota', 'model': 'Tundra Regular Cab'},
        {'make': 'Toyota', 'model': 'Venza'},
        {'make': 'Toyota', 'model': 'Yaris Hatchback'},
        {'make': 'Toyota', 'model': 'Yaris iA'},
        {'make': 'Toyota', 'model': 'Yaris'},
        {'make': 'Toyota', 'model': 'bZ4X'},
        {'make': 'VinFast', 'model': 'VF 8'},
        {'make': 'VinFast', 'model': 'VF 9'},
        {'make': 'Volkswagen', 'model': 'Arteon'},
        {'make': 'Volkswagen', 'model': 'Atlas Cross Sport'},
        {'make': 'Volkswagen', 'model': 'Atlas'},
        {'make': 'Volkswagen', 'model': 'Beetle'},
        {'make': 'Volkswagen', 'model': 'CC'},
        {'make': 'Volkswagen', 'model': 'Cabrio'},
        {'make': 'Volkswagen', 'model': 'Eos'},
        {'make': 'Volkswagen', 'model': 'Eurovan'},
        {'make': 'Volkswagen', 'model': 'GLI'},
        {'make': 'Volkswagen', 'model': 'GTI'},
        {'make': 'Volkswagen', 'model': 'Golf Alltrack'},
        {'make': 'Volkswagen', 'model': 'Golf GTI'},
        {'make': 'Volkswagen', 'model': 'Golf R'},
        {'make': 'Volkswagen', 'model': 'Golf SportWagen'},
        {'make': 'Volkswagen', 'model': 'Golf'},
        {'make': 'Volkswagen', 'model': 'ID.4'},
        {'make': 'Volkswagen', 'model': 'Jetta (New)'},
        {'make': 'Volkswagen', 'model': 'Jetta GLI'},
        {'make': 'Volkswagen', 'model': 'Jetta SportWagen'},
        {'make': 'Volkswagen', 'model': 'Jetta'},
        {'make': 'Volkswagen', 'model': 'New Beetle'},
        {'make': 'Volkswagen', 'model': 'Passat (New)'},
        {'make': 'Volkswagen', 'model': 'Passat'},
        {'make': 'Volkswagen', 'model': 'Phaeton'},
        {'make': 'Volkswagen', 'model': 'R32'},
        {'make': 'Volkswagen', 'model': 'Rabbit'},
        {'make': 'Volkswagen', 'model': 'Routan'},
        {'make': 'Volkswagen', 'model': 'Taos'},
        {'make': 'Volkswagen', 'model': 'Tiguan Limited'},
        {'make': 'Volkswagen', 'model': 'Tiguan'},
        {'make': 'Volkswagen', 'model': 'Touareg 2'},
        {'make': 'Volkswagen', 'model': 'Touareg'},
        {'make': 'Volkswagen', 'model': 'e-Golf'},
        {'make': 'Volvo', 'model': 'C30'},
        {'make': 'Volvo', 'model': 'C40 Recharge'},
        {'make': 'Volvo', 'model': 'C70'},
        {'make': 'Volvo', 'model': 'S40 (New)'},
        {'make': 'Volvo', 'model': 'S40'},
        {'make': 'Volvo', 'model': 'S60'},
        {'make': 'Volvo', 'model': 'S70'},
        {'make': 'Volvo', 'model': 'S80'},
        {'make': 'Volvo', 'model': 'S90'},
        {'make': 'Volvo', 'model': 'V40'},
        {'make': 'Volvo', 'model': 'V50'},
        {'make': 'Volvo', 'model': 'V60'},
        {'make': 'Volvo', 'model': 'V70'},
        {'make': 'Volvo', 'model': 'V90'},
        {'make': 'Volvo', 'model': 'XC40 Recharge'},
        {'make': 'Volvo', 'model': 'XC40'},
        {'make': 'Volvo', 'model': 'XC60'},
        {'make': 'Volvo', 'model': 'XC70'},
        {'make': 'Volvo', 'model': 'XC90'},
        {'make': 'smart', 'model': 'fortwo EQ cabrio'},
        {'make': 'smart', 'model': 'fortwo EQ coupe'},
        {'make': 'smart', 'model': 'fortwo cabrio'},
        {'make': 'smart', 'model': 'fortwo electric drive cabrio'},
        {'make': 'smart', 'model': 'fortwo electric drive'},
        {'make': 'smart', 'model': 'fortwo'},
    ]  # Add all car models with their corresponding make and category

    for data in car_models_data:
        make_name = data['make']

        car_make_obj = CarMake.objects.get(make=make_name)

        CarModel.objects.create(
            model=data['model'],
            make=car_make_obj,
        )


def delete_car_models(apps, schema_editor):
    CarModel = apps.get_model('car_app', 'CarModel')
    CarModel.objects.all().delete()


def delete_car_makes(apps, schema_editor):
    CarMake = apps.get_model('car_app', 'CarMake')
    CarMake.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('car_app', '0001_initial'),
        # Add the dependency to the previous migration file if any
    ]

    operations = [
        migrations.RunPython(populate_car_makes, delete_car_makes),
        migrations.RunPython(populate_car_models, delete_car_models)
    ]
