# Generated by Django 4.2.1 on 2023-07-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocarmodel',
            name='photos',
        ),
        migrations.AddField(
            model_name='photocarmodel',
            name='car_image_specs',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
    ]
