# Generated by Django 4.2.1 on 2023-07-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_remove_photocarmodel_photos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocarmodel',
            old_name='car_image_specs',
            new_name='image',
        ),
    ]
