# Generated by Django 4.2.1 on 2023-07-11 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_carlisting_engine_litres_alter_carlisting_body_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='engine_litres',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(8, message="There's no bigger car engine than 8 litres.")], verbose_name='Engine Litres'),
        ),
    ]
