# Generated by Django 4.2.1 on 2023-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_alter_carlisting_engine_litres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='euro',
            field=models.CharField(choices=[('Euro_1', 'Euro 1'), ('Euro_2', 'Euro 2'), ('Euro_3', 'Euro 3'), ('Euro_4', 'Euro 4'), ('Euro_5', 'Euro 5'), ('Euro_6', 'Euro 6')], max_length=6, verbose_name='Euro'),
        ),
    ]
