# Generated by Django 4.2.1 on 2023-07-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0007_alter_carlisting_euro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='euro',
            field=models.CharField(choices=[('1', 'Euro 1'), ('2', 'Euro 2'), ('3', 'Euro 3'), ('4', 'Euro 4'), ('5', 'Euro 5'), ('6', 'Euro 6')], max_length=6, verbose_name='Euro'),
        ),
    ]
