# Generated by Django 4.2.1 on 2023-07-20 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0008_alter_carlisting_euro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='color',
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='engine_litres',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='You cannot have an engine below 0.0 litres.'), django.core.validators.MaxValueValidator(8, message="There's no bigger car engine than 8 litres.")], verbose_name='Engine Litres'),
        ),
    ]
