# Generated by Django 4.2.1 on 2023-07-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0012_alter_photocarmodel_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocarmodel',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.carlisting'),
        ),
    ]
