# Generated by Django 4.2.1 on 2023-08-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0014_alter_photocarmodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
