# Generated by Django 4.2.1 on 2023-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0015_carlisting_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='price',
            field=models.PositiveIntegerField(verbose_name='$/Day'),
        ),
    ]
