# Generated by Django 4.2.1 on 2023-06-26 09:03

import CarRental.core.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(6), CarRental.core.utils.check_username_starts_with_letter])),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='Age')),
                ('country', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
