# Generated by Django 4.2.1 on 2023-07-04 09:13

import CarRental.common.validators
import CarRental.core.utils
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(6), CarRental.common.validators.check_username_starts_with_letter], verbose_name='Username')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Image')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(inverse_match=True, message='This field can contain only characters.', regex='[a-zA-Z]+')], verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(inverse_match=True, message='This field can contain only characters.', regex='[a-zA-Z]+')], verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(blank=True, default=18, null=True, validators=[django.core.validators.MinValueValidator(18, message='You have to be between 18 and 70 to rent a car.'), django.core.validators.MaxValueValidator(70, message='You have to be between 18 and 70 to rent a car.')], verbose_name='Age')),
                ('country', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(inverse_match=True, message='This field can contain only characters.', regex='[a-zA-Z]+')], verbose_name='Country')),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True, validators=[CarRental.common.validators.validate_phone_number_starts_with_zero], verbose_name='Phone Number')),
                ('city', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='This field can contain only characters.', regex='[a-zA-Z]+')], verbose_name='City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
