# Generated by Django 4.2.1 on 2023-06-26 09:19

import CarRental.core.utils
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(6), CarRental.core.utils.check_username_starts_with_letter, CarRental.core.utils.validate_username_only_letters_and_numbers], verbose_name='Username'),
        ),
    ]
