# Generated by Django 4.2.1 on 2023-06-29 14:19

import CarRental.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[CarRental.common.validators.validate_only_characters], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), CarRental.common.validators.validate_only_characters], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3), CarRental.common.validators.validate_only_characters], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3), CarRental.common.validators.validate_only_characters], verbose_name='Last Name'),
        ),
    ]
