# Generated by Django 4.2.1 on 2023-06-26 17:19

import CarRental.core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_appuser_managers_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(6), CarRental.core.utils.check_username_starts_with_letter], verbose_name='Username'),
        ),
    ]
