# Generated by Django 4.2.1 on 2023-06-28 11:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_appuser_is_staff_appuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
