# Generated by Django 4.2.1 on 2023-07-04 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_contactusmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(inverse_match=False, message='First Name field can contain only characters.', regex='[a-zA-Z]+')], verbose_name='First Name'),
        ),
    ]
