# Generated by Django 4.2.1 on 2023-06-28 11:43

import CarRental.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_profileuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[CarRental.common.validators.validate_phone_number_length], verbose_name='Phone Number'),
        ),
    ]
