# Generated by Django 4.2.1 on 2023-07-11 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_appuser_groups_appuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
