# Generated by Django 4.2.1 on 2023-06-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_profileuser_age_alter_profileuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
