# Generated by Django 4.2.1 on 2023-06-28 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_profileuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
