# Generated by Django 4.2.1 on 2023-07-11 13:30

import CarRental.common.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0008_contactusmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='admin_message',
            field=models.CharField(choices=[('Unread', 'Unread',), ('READ', 'Read')], default='Unread', max_length=6,
                                   null=True),
        ),
    ]
