# Generated by Django 4.2.1 on 2023-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0009_contactusmodel_admin_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='admin_message',
            field=models.CharField(choices=[('Unread',), ('READ', 'Read')], default='Unread', max_length=6, null=True),
        ),
    ]
