# Generated by Django 4.2.1 on 2023-06-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_profileuser_profile_image_alter_profileuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Image'),
        ),
    ]
