# Generated by Django 4.2.1 on 2023-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_contactusmodel_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved'), ('Unsolved', 'Unsolved')], default='Pending', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='admin_message',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=6, null=True),
        ),
    ]
