# Generated by Django 4.2.1 on 2023-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_contactusmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=60, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
