# Generated by Django 4.2.1 on 2023-07-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_appuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us Requests'},
        ),
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name': 'User Profile'},
        ),
    ]
