# Generated by Django 4.2.1 on 2023-08-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_appuser_email_token_appuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='email_token',
        ),
    ]
