# Generated by Django 4.2.1 on 2023-08-07 11:18

import CarRental.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_appuser_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[CarRental.common.validators.validate_image_size], verbose_name='Profile Image'),
        ),
    ]
