# Generated by Django 4.2.1 on 2023-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_profileuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='revenue_last_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='revenue_last_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='revenue_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='revenue_yesterday',
            field=models.IntegerField(default=0),
        ),
    ]
