# Generated by Django 4.2.1 on 2023-08-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_profileuser_total_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='revenue_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
