# Generated by Django 4.2.1 on 2023-08-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_profileuser_revenue_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='revenue_last_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='revenue_last_week',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='revenue_yesterday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
